config/routes.rb
Rails.application.routes.draw do

  localized do
    root 'users#home'
    delete 'delete_user', to: 'users#destroy'
    get 'account_locked', to: 'users#account_locked'

    devise_for :users, path: '', path_names:
    { sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register',
    edit: 'settings' }

    resources :users do
      post 'update'
      get 'profile'
    end
  end

  get '/de', to: 'users#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ruby_alias.rb
class RubyAlias < ApplicationRecord
end

app/models/ruby_call.rb
class RubyCall < ApplicationRecord
end

app/models/ruby_method.rb
class RubyMethod < ApplicationRecord
  has_many :ruby_aliases
  has_many :ruby_calls
  has_many :users_ruby_methods
  has_many :users, through: :users_ruby_methods

  # Return date, when the method was created for particular User
  def get_created_date(user_id)
    users_ruby_methods.find_by(user_id: user_id).created_at
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable
  has_many :users_ruby_methods
  has_many :ruby_methods, through: :users_ruby_methods

  def generate_new_ruby_method
    generated_method = RubyMethod.offset(rand(RubyMethod.count)).first
    if ruby_methods.include?(generated_method)
      generate_new_ruby_method
    else
      ruby_methods << generated_method
    end
  end

  def get_latest_method
    latest_method = users_ruby_methods.sort_by(&:created_at).reverse.first
    RubyMethod.find(latest_method.ruby_method_id)
  end
end

app/models/users_ruby_method.rb
class UsersRubyMethod < ApplicationRecord
  belongs_to :user
  belongs_to :ruby_method
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:title, :name, :last_name, :email])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_activated?, except: :account_locked
  before_action :authenticate_user!, only: [:destroy, :index, :profile, :update]

  layout false, only: :update

  def home
    return redirect_to user_profile_path(user_id: current_user.id) if user_signed_in?

    render 'home'
  end

  def account_locked
    render 'account_locked'
  end

  def index
    if user_signed_in? && current_user.is_admin?
      @users = User.order(:name).page(params[:page]).decorate
      render 'list_user'
    else
      redirect_to root_path
    end
  end

  def profile
    user = current_user
    @methods = user.ruby_methods.reverse.drop(1)
    @methods = user.generate_new_ruby_method if @methods.count == 0
    @method = user.get_latest_method
    render 'profile'
  end

  def destroy
    id = params[:id]
    if can_destroy_user? id
      user = User.find(id).destroy
      flash[:success] = t('user_destroyed', user_name: user.name)
    else
      flash[:danger] = t('cant_delete_yourself')
    end
    redirect_to users_path
  end

  def update
    id = params[:user_id]
    @user = User.find(id)

    if !@user.is_admin? && @user.update_attributes(is_activated: params[:completed])
      @message = {message: t('user_updated', user_name: @user.name), button: 'OK'}
    else
      @message = {message: t('cant_deactivate_admin'), button: 'OK'}
    end
    render 'shared/_snackbar'
  end

  private

  # Defines, whether the user is allowed to destroy other users (excluding himself)
  def can_destroy_user?(id)
    params_id = id.to_i
    current_id = current_user.id

    current_user.is_admin? && params_id != current_id
  end

  # redirects to locker account page if user is not activated
  def is_activated?
    redirect_to account_locked_path if user_signed_in? && !current_user.is_activated?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Ruby of the Day'
    page_title.empty? ? base_title : (page_title + ' | ' + base_title)
  end

end

app/helpers/mailer_helper.rb
module MailerHelper

  def email_image_tag(image, **options)
    attachments.inline[image] = File.read(Rails.root.join("app/assets/images/#{image}"))
    image_tag attachments[image].url, **options
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_favicon.html.slim
| <link rel="apple-touch-icon" sizes="180x180" href="
= asset_path 'favicon/apple-touch-icon.png'
| "> <link rel="icon" type="image/png" sizes="32x32" href="
= asset_path 'favicon/favicon-32x32.png'
| "> <link rel="icon" type="image/png" sizes="16x16" href="
= asset_path 'favicon/favicon-16x16.png'
| "> <link rel="manifest" href="
= asset_path 'favicon/manifest.json'
| "> <link rel="mask-icon" href="
= asset_path 'favicon/safari-pinned-tab.svg'
| " color="#5bbad5"> <link rel="shortcut icon" href="
= asset_path 'favicon/favicon.ico'
| "> <meta name="msapplication-config" content="
= asset_path 'favicon/browserconfig.xml'
| "> 
meta[name="theme-color" content="#ffffff"]

app/views/layouts/application.html.slim
doctype html
html
  head
    title == full_title(yield(:title))
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="theme-color" content="#222"
    = render 'application/favicon'
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'shared/header'

    main.container
      - flash.each do |message_type, message|
        div.alert.alert-dismissable{class="alert-#{message_type}"}
          button.close{type="button" data-dismiss="alert"} &times;
          = message
      = yield

app/views/shared/_header.html.slim
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#navbar-collapse'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag 'ruby.svg', alt: 'Ruby of the day'
        span Ruby of the Day

    .collapse.navbar-collapse#navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li = link_to t('users'), users_path if current_user.is_admin?
          li.dropdown.btn-group
            a.dropdown-toggle data-toggle='dropdown' href='#'
              = current_user.email
              span.caret
            ul.dropdown-menu role='menu'
              li= link_to t('show_profile'), user_profile_path(user_id: current_user.id)
              li= link_to t('change_profile'), edit_user_registration_path
              li= link_to t('logout'), destroy_user_session_path, method: :delete
        - else
          li= link_to t('login'), new_user_session_path
          li= link_to t('sign_up'), new_user_registration_path
        li.dropdown.btn-group
          = link_to '#', class: 'dropdown-toggle', 'data-toggle': 'dropdown' do
            span.lang-sm[lang="#{I18n.locale}"]
          ul.dropdown-menu role='menu'
            - I18n.available_locales.each do |locale|
              li
                = link_to "/#{locale}" do
                  span.lang-sm.lang-lbl[lang="#{locale}"]

app/views/shared/_show_user_method.html.slim
h3= t('method_today', date: l(Time.current.to_date))
h2.ruby-method-heading
  = @method.name + ' '
  small= "[#{@method.ruby_class}]"

- for ruby_call in @method.ruby_calls
  code.ruby-code == ruby_call[:name]

p == @method.description
a href="https://ruby-doc.org/core-2.4.1/#{@method.url}"= "https://ruby-doc.org/core-2.4.1/#{@method.url}"
p == @method.detail

app/views/shared/_snackbar.html.slim
.snackbar
  .snackbar-message = @message[:message]
  .snackbar-action
    button= @message[:button]

app/views/users/account_locked.html.slim
.row
  .col-md-2
  .col-md-8
    .jumbotron
      h2.text-danger.jumbo-danger-heading= t('account_locked')
      p
        strong= t('reason')
        = t('account_locked_explanation')
      p
        a.btn.btn-danger.btn-lg[href="mailto:admin@rubyoftheday.de"] admin@rubyoftheday.de
  .col-md-2

app/views/users/home.html.slim
= provide(:title, 'Home')

h1 Ruby of the Day
p== t('landing_page_welcome_text')
= link_to t('sign_up'), new_user_session_path, class: 'btn btn-danger'

app/views/users/list_user.html.slim
h2 List of all users
div.table-responsive
  table.table.table-striped.table-hover.table-condensed
    thead
      tr
        th= t('table_name')
        th= t('table_registered')
        th Admin?
        th= t('table_active')
        th
    tbody
      - for user in @users
        tr
          td = user.shortened_name
          td = l(user.created_at, format: :short)
          td = user.is_admin? ? t('yes') : t('no')
          td = check_box_tag user.id, user.is_activated, user.is_activated, class: 'activate-account', disabled: user.is_admin?
          td = link_to t('delete'), delete_user_path(id: user.id), method: :delete,
                  data: {confirm: t('confirm_delete_user', user_name: user.name)} unless user.is_admin?

= paginate @users

app/views/users/profile.html.slim
= render 'shared/show_user_method'
br
.row
  .col-md-6
    h3= t('send_methods')
    div.table-responsive
      table.table.table-condensed
        thead
          tr
            th = t('sent_at')
            th = t('method')
        tbody
          - @methods.each do |method|
            tr
              td = l method.get_created_date(current_user.id), format: :short
              td
                = method.name
                small = " [#{method.ruby_class}]"
  .col-md-6
    h3= t('search')
    = form_tag users_path, method: 'get', id: 'search-form' do
      = text_field_tag :search, params[:search], placeholder: t('search_placeholder')
      = submit_tag t('do_search'), class: 'btn btn-default btn-sm'